# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, macos]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace CiCdReactNative.xcworkspace -scheme CiCdReactNative archive -archivePath CiCdReactNative.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./CiCdReactNative.xcarchive -exportPath . -exportOptionsPlist CiCdReactNative/Info.plist
          mv CiCdReactNative.ipa ../CiCdReactNative.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: CiCdReactNative.ipa
          path: ios/build/

